apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  #serviceName: "helloworld"
  replicas: 2
  selector:
    matchLabels:
       app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      # soft antiaffinity for optimize placement
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: 
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - helloworld
              topologyKey: kubernetes.io/hostname
      containers:
      - name: helloworld
        #image: 172.16.155.136:5000/emotibot-k8s/uwebserverv6
        image: 172.16.155.136:5000/uwebserverv6

        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5

        stdin: true
        securityContext:
          privileged: true
          capabilities:
             add:
               - NET_ADMIN
        ports:
          - containerPort: 8000
        resources:
          limits:
            cpu: 0.3 
            memory: 256Mi
          requests:
            cpu: 0.3
            memory: 256Mi

        volumeMounts:
        - mountPath: /etc/localtime
          name: hosttime
        - mountPath: /var/log/web
          name: loggerfile
      volumes:
       - name: hosttime
         hostPath:
           path: /etc/localtime 
       - name: loggerfile
         hostPath:
           path: /var/log/containerlogger/web
      #select node label if enable
      #nodeSelector:
      #  ebotrole: worker
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
  - name: http
    protocol: TCP
    #port is loadbalancer port
    port: 8001
    # targetport is container port
    targetPort: 8000
  selector:
    app: helloworld

